DROP table if exists schedule;

create table if not exists schedule (id int8 generated by default as identity, day_of_week varchar(255) not null, start_time time not null, end_time time not null, primary key (id));
create table if not exists schedule_course (schedule_id int8 not null, course_id int8 not null);

alter table if exists schedule_course add constraint FK_course foreign key (course_id) references course on delete cascade;
alter table if exists schedule_course add constraint FK_schedule foreign key (schedule_id) references schedule on delete cascade;
